server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      data-locations: classpath*:database/h2/data.sql
      schema-locations: classpath*:database/h2/schema.sql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    port: 6379
    host: 127.0.0.1

logging:
  level:
    org.hibernate.SQL: debug
