create table coffee_menu (
    coffee_menu_id bigint generated by default as identity,
    created_date timestamp,
    modified_date timestamp,
    name varchar(255) not null,
    price integer not null,
    primary key (coffee_menu_id)
);

create table popular_coffee_menu (
    coffee_menu_id bigint not null,
    order_count integer not null,
    primary key (coffee_menu_id)
);

create table users (
    user_id bigint generated by default as identity,
    created_date timestamp,
    modified_date timestamp,
    name varchar(255),
    primary key (user_id)
);

create table point (
    id bigint generated by default as identity,
    created_date timestamp,
    modified_date timestamp,
    point integer not null,
    user_id bigint,
    primary key (id)
);

create table orders (
    order_id bigint generated by default as identity,
    created_date timestamp,
    modified_date timestamp,
    user_id bigint,
    primary key (order_id)
);

create table order_detail (
    id bigint generated by default as identity,
    created_date timestamp,
    modified_date timestamp,
    price integer not null,
    quantity integer not null,
    coffee_menu_id bigint,
    order_id bigint,
    primary key (id)
);